github: [mind-Expanders, lockismdottech]
patreon: ibnearshaddotcom
buy_me_a_coffee: ibnearshaddotcom
custom: ['https://www.mindexpanders.org/', 'https://lockism.tech/', 'https://www.mindsters.org/', 'https://vestazone.com/']
